# Numpy Arrays

In [11]:
my_list=[1,2,3]

In [12]:
import numpy as np

In [13]:
arr = np.array(my_list)

In [14]:
arr

array([1, 2, 3])

# 2-D array using lists

In [15]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

# Identity matrix (a square matrix which has diagonal 1's)

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# random() value matrix (value=0-1)

In [25]:
np.random.rand(3)

array([0.98064859, 0.73931755, 0.59589202])

In [26]:
np.random.rand(3,4)

array([[0.87985553, 0.3251191 , 0.42498206, 0.90840108],
       [0.11572858, 0.20633514, 0.46316484, 0.64206889],
       [0.60506352, 0.39633837, 0.66150757, 0.13820815]])

In [29]:
np.random.randn(4,3)

array([[-1.12799307,  0.44814401, -1.01716915],
       [-0.69960125, -0.87705599,  1.68237032],
       [-0.14169036, -2.08463204,  0.35583091],
       [-1.63826099, -1.35988278,  0.35770057]])

In [30]:
np.random.randint(1,100,15)

array([68, 20, 63, 88, 90, 77,  3, 11, 88, 10, 73,  8, 84, 98, 88])

# reshape() is used to re-arrange the values to a respective matrix size

In [33]:
arr=np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape    #to find the matrix size/shape

(25,)

# Min() , Max()

In [43]:
ranarr=np.random.randint(0,100,15)

In [44]:
ranarr

array([74, 98, 30, 60, 32, 76, 49, 34, 39, 86, 74, 66, 28, 91, 32])

In [45]:
ranarr.min()

28

In [46]:
ranarr.max()

98

In [48]:
ranarr.argmin()  #returns the minimum value index

12

In [49]:
ranarr.argmax()  #returns the maximun value index

1

# dtype is used to find the datatype of the array

In [54]:
arr.dtype

dtype('int32')