# NumPy Indexing and Solution

In [1]:
import numpy as np

In [33]:
arr=np.arange(50).reshape(5,10)

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
arr[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
arr[2,1]  #or arr[2][1]

21

In [43]:
arr[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [17]:
arr=np.arange(1,10)

In [18]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr_bool=arr>5
arr_bool

array([False, False, False, False, False,  True,  True,  True,  True])

In [24]:
arr[arr_bool]

array([6, 7, 8, 9])

In [25]:
arr[arr>6]

array([7, 8, 9])